baseURL = ""
languageCode = "ja"
title = "BBTAG虎の巻"
theme = "learn"
relativeURLs = true

[params]
  author = "ptrst102"
  disableLandingPageButton = false
  disableBreadcrumb = false
  disableNextPrev = true
  titleSeparator = "|"
  themeVariant = "green"

[markup]
  [markup.goldmark]

[markup.goldmark.renderer]
  hardWraps = true

[outputs]
  home = [ "HTML", "RSS", "JSON"]